export const APP_IMAGES = {
  ME_IMAGE: { image: '/images/me.png', alt: 'chacaponquin_avatar' },
  CHACA_NPM_IMAGE: { image: '/images/chaca_npm.webp', alt: 'chaca_image' },
  CHACA_WEB_IMAGE: { image: '/images/chaca_web.webp', alt: 'chaca_web_image' },
  CRYPTO_IMAGE: { image: '/images/crypto.webp', alt: 'ch_crypto_app' },
  CHACA_DOCS_IMAGE: { image: '/images/chaca-doc.webp', alt: 'chaca-docs' },
  LOGO: { image: '/logo/portfolio_logo.png', alt: 'hector_portfolio_logo' },
  ABOUT_ME: { image: '/images/about-me.png', alt: 'hector-about-me' },
  SKILLS: {
    CSS: { image: '/images/skills/css.svg', alt: 'css' },
    EXPRESS: { image: '/images/skills/express.svg', alt: 'express' },
    GIT: { image: '/images/skills/git.svg', alt: 'git' },
    HTML: { image: '/images/skills/html.svg', alt: 'html' },
    JS: { image: '/images/skills/javascript.svg', alt: 'javascript' },
    MONGODB: { image: '/images/skills/mongodb.svg', alt: 'mongodb' },
    NEXT: { image: '/images/skills/next.svg', alt: 'nextjs' },
    PYTHON: { image: '/images/skills/python.svg', alt: 'python' },
    TAILWIND: { image: '/images/skills/tailwindcss.svg', alt: 'tailwind' },
    TS: { image: '/images/skills/typescript.svg', alt: 'typescript' },
    POSTGRESQL: { image: '/images/skills/postgresql.svg', alt: 'postgresql' },
    DOCKER: { image: '/images/skills/docker.svg', alt: 'docker' },
    GO: { image: '/images/skills/go.svg', alt: 'golang' },
    REACT: { image: '/images/skills/react.svg', alt: 'react' },
    GRAPHQL: { image: '/images/skills/graphql.svg', alt: 'graphql' },
    NESTJS: { image: '/images/skills/nestjs.svg', alt: 'nestjs' },
    ANGULAR: { image: '/images/skills/angular.svg', alt: 'angular' },
  },
} as const
